language: ruby
cache: bundler

rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

sudo: false

script: "bundle exec rake clean spec"

notifications:
  email:
    - james@jamesrgifford.com
    - scott@artsicle.com
